### ISSUE TITLE
New Event: "Near Miss"

### ISSUE THREAD

**Issue by ForeDaMole** [MoreEventsMod/More_Events_Mod_Beta#213] opened 2016-09-17 20:00 UTC
This is a proposed event.

This event would occur on any colonized world with a regular (I.E. not a black hole) sun.

Upon occurrence:
**Near Miss**
_“Scientists on [Planet Name] were surprised to register an immense solar “superstorm” bypassing the [Planet/Moon]. The storm, a coronal mass ejection that had apparently been missed by sensors until nearly striking the colony, could have caused widespread and in many cases irreparable damage to the electronic infrastructure of [Planet Name]. Had the ejection hit the world, who knows how many could have died in the ensuing chaos.”_

Options:
ONLY IF DESPICABLE NEUTRALS
“Meh.”

> Nothing happens.

ONLY IF MATERIALIST
“Such a possibility hangs over our heads every day... terrifying.”

> Planet gains the “Near Miss” modifier, imparting -10% happiness for 5 years.

ONLY IF SPIRITUALIST
“It is a sign of divine intervention that the planet was saved!”

> Planet gains the “Near Miss” modifier, imparting +10% happiness for 5 years.

ONLY IF XENOPHILE
“The more worlds we colonize, the less damage that kind of event can do.”

> Planet gains the “Near Miss” modifier, imparting -10% growth time (making the planet grow more) for 5 years.

ONLY IF XENOPHOBE
“Such a thing would never happen on our homeworld. Who would curse their children to be born on an alien planet?”

> Planet gains the “Near Miss” modifier, imparting +10% growth time (making the planet grow slower) for 5 years.

ONLY IF INDIVIDUALIST
“Our colonists will no doubt experiment more with their lives now that they know how little time they have.”

> Planet gains the “Near Miss” modifier, imparting +10% ethics divergence for 5 years.

ONLY IF COLLECTIVIST
“This should remind our colonists of the value of working together while they still can.”

> Planet gains the “Near Miss” modifier, imparting -10% ethics divergence for 5 years.

**Comment by tzerrell** [comment] 2016-10-02 21:25
This event is now in `dev` and is ready for testing and translation. Test with `event mem_near_miss.1` with a planet you own selected. This should be tested with various ethics (see above for which ones).

**Comment by Deytron** [comment] 2016-10-03 14:45
The event is working  as intended, with a different effect for every empire type, but the sentences are too long, and thus, don't fit in the dialog boxes. Some screenshots : 

![image](https://cloud.githubusercontent.com/assets/20344764/19041510/abd3a626-8988-11e6-88aa-c5d2fb7fa100.png)

![image](https://cloud.githubusercontent.com/assets/20344764/19041517/b0f01ac2-8988-11e6-98c9-909ce841483c.png)

![image](https://cloud.githubusercontent.com/assets/20344764/19041522/b416d10a-8988-11e6-9954-a2c456b6b25d.png)

Also, it looks like there's a question mark missing.
![image](https://cloud.githubusercontent.com/assets/20344764/19041529/bcc14b46-8988-11e6-9fd2-0a67367721f9.png)

**Comment by tzerrell** [comment] 2016-10-04 21:29
Thanks @Deytron , these are now fixed.

**Closed as completed by tzerrell** 2016-10-04 21:29 UTC
Labels: needs testing, event
